version: '3'

networks:
  default:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yummycorp-web
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html/laravel
    networks:
      - default

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - default

  mysql:
    platform: linux/x86_64
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - '33061:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql


